# Generated by Django 3.2.9 on 2021-12-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='news.newscomments'),
        ),
        migrations.AlterField(
            model_name='news',
            name='stars',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
