# Generated by Django 3.2.9 on 2022-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomments',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
