# Generated by Django 3.2.9 on 2022-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscomments_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomments',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='news',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
