# Generated by Django 3.2.9 on 2022-03-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220319_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='likes',
            new_name='users_who_liked',
        ),
    ]
