# Generated by Django 3.2.9 on 2022-02-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220202_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
    ]
