# Generated by Django 3.2.9 on 2022-02-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_news_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomments',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
