# Generated by Django 3.2.9 on 2022-03-20 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_auto_20220320_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
