# Generated by Django 3.2.9 on 2022-03-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_newscomments_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='newscomments',
            name='stars',
        ),
    ]
