# Generated by Django 3.2.9 on 2022-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('koban_type', models.CharField(choices=[('DO', 'Do'), ('IN', 'In process'), ('DN', 'Done')], default='DO', max_length=2)),
                ('data_start', models.DateTimeField(auto_now_add=True)),
                ('data_end', models.DateTimeField(null=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
                ('price', models.FloatField()),
                ('run_time', models.DurationField(null=True)),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
