# Generated by Django 3.2.9 on 2021-12-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.orders'),
        ),
        migrations.AlterField(
            model_name='services',
            name='run_time',
            field=models.DurationField(null=True),
        ),
    ]
