# Generated by Django 3.2.9 on 2022-03-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-data_start']},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='koban_type',
            new_name='kanban_type',
        ),
    ]
