# Generated by Django 3.2.9 on 2021-12-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20211222_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
