# Generated by Django 3.2.9 on 2021-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_services_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-price']},
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
