# Generated by Django 3.2.9 on 2022-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20220312_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercomments',
            name='title',
        ),
        migrations.AlterField(
            model_name='orders',
            name='kanban_type',
            field=models.CharField(choices=[('DO', 'Do'), ('IN', 'In process'), ('DN', 'Done'), ('AR', 'Archive')], default='DO', max_length=2),
        ),
    ]
