# Generated by Django 3.2.9 on 2022-03-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_ordercomments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
