# Generated by Django 3.2.9 on 2022-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_orders_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
    ]
