""" credits.py """
PROJECT_SECRET_KEY = 'DJANGO_SECRET_KEY'

# Database
DB_NAME = 'DATABASE_NAME'
DB_USER = 'DATABASE_USER'
DB_PASSWORD = 'DATABASE_PASSWORD'
DB_HOST = 'DATABASE_HOST'
DB_PORT = 'DATABASE_PORT'
